name: PR CI - Build and Test

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore BusOps.sln
    
    - name: Build solution
      run: dotnet build BusOps.sln --configuration Release --no-restore
    
    - name: Run unit tests
      run: dotnet test tests/BusOps.Tests/BusOps.Tests.csproj --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"
    
    - name: Run integration tests
      run: dotnet test tests/BusOps.IntegrationTests/BusOps.IntegrationTests.csproj --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=integration-test-results.trx"
      continue-on-error: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}
        path: |
          **/TestResults/**/*.trx
          **/TestResults/**/*.xml
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: matrix.os == 'ubuntu-latest'
      with:
        name: coverage-reports
        path: |
          **/TestResults/**/coverage.cobertura.xml
    
    - name: Publish Test Results (Linux)
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!cancelled()) && matrix.os == 'ubuntu-latest'
      with:
        files: |
          **/TestResults/**/*.trx
        check_name: Test Results (${{ matrix.os }})
    
    - name: Publish Test Results (macOS)
      uses: EnricoMi/publish-unit-test-result-action/macos@v2
      if: (!cancelled()) && matrix.os == 'macos-latest'
      with:
        files: |
          **/TestResults/**/*.trx
        check_name: Test Results (${{ matrix.os }})
    
    - name: Publish Test Results (Windows)
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: (!cancelled()) && matrix.os == 'windows-latest'
      with:
        files: |
          **/TestResults/**/*.trx
        check_name: Test Results (${{ matrix.os }})

  code-coverage:
    name: Code Coverage Report
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore BusOps.sln
    
    - name: Build solution
      run: dotnet build BusOps.sln --configuration Debug --no-restore
    
    - name: Run tests with coverage
      run: dotnet test BusOps.sln --configuration Debug --no-build --verbosity minimal --collect:"XPlat Code Coverage" --results-directory ./coverage
    
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    
    - name: Generate coverage report
      run: reportgenerator -reports:"./coverage/**/coverage.cobertura.xml" -targetdir:"./coverage/report" -reporttypes:"Cobertura;MarkdownSummaryGithub" -verbosity:Info
    
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/report/Cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '60 80'
    
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
    
    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore BusOps.sln
    
    - name: Check formatting
      run: dotnet format BusOps.sln --verify-no-changes --verbosity diagnostic
      continue-on-error: true
